### ISSUE TITLE
Milestone 3: Gateway

### ISSUE THREAD

**Issue by gsvarovsky** [m-ld/web-zero#5]
> We will develop an open source server application that provides secure, durable storage of data,
and a message delivery mechanism, for collaborative web apps using m-ld. We will provide a
hosted instance of this server as a service for testing by third parties without setup.
> - 3.1. Gateway source code, providing (optional) durable data storage and (optional) message delivery
> - 3.2. Deployed online Gateway service
> - 3.3. Service security specification, including handling of personal data

**Comment by gsvarovsky** [comment]
Todo
- [x] m-ld/m-ld-gateway#11
- [x] m-ld/m-ld-gateway#7
- [x] Landing page on gw.m-ld.org (ready for m-ld/m-ld-gateway#6)
- [x] ~~Docs published to doc.gw.m-ld.org on CDN~~ _hosted on gw.m-ld.org_
- [x] Security docs with personal data handling
- [x] Self-hosting docs

**Comment by gsvarovsky** [comment]
## outcome

- The gateway repository is https://github.com/m-ld/m-ld-gateway
- The online service and usage documentation is deployed at https://gw.m-ld.org/ – including instructions for self-hosting
- The architecture is a directory in the repository, with a security section

### notable benefits

- The demo project at https://github.com/m-ld/m-ld-todomvc-vanillajs has been updated to use the gateway – and so, it has no build step any more 🎉
- The Gateway is designed to also be used as a 'sidecar' engine for server-side use-cases of m-ld, something we've talked about many times, e.g. for PHP environments
- We have refactored the m-ld compliance test suite to use a new package [m-ld-test](https://github.com/m-ld/m-ld-test), which is shared with the Gateway for load simulation (see the gateway `sim` directory)

### next steps

- Update the Getting Started section at https://js.m-ld.org/ to suggest use of the Gateway (as part of overhauling the m-ld documentation in general)
- Enhance the [m-ld playground](https://m-ld.org/playground/) to work with Gateway domains
- Improve the documentation and functionality of the Gateway as required by users (including ourselves)
- Throttle and limit over-usage to save costs, if required! (would be a nice problem to have)
- Create a test/example project for 'sidecar' use of the Gateway – this would also fulfil the desire for a m-ld/m-ld-spec#41
- Run the m-ld compliance tests on the Gateway (now possible due to the m-ld-test library)
- Enable clustering of the Gateway – requires m-ld/m-ld-gateway#2
- As part of #7 we will ensure that the Gateway supports apps using alternative authentication protocols, such as OPAQUE
- Perform a Security audit (provided by Radically Open Security)
- Outreach to find collaborators and users! 👀
